[package]
name = "cleo"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["json"] }
serde = "1.0.210"
serde_json = "1.0.128"
serenity = "0.12.2"
tantivy = "0.22.0"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"]}
